import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import fs from "fs";
import path from "path";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// === НАСТРОЙКИ СИНХРОНИЗАЦИИ ===

// Путь к плагину в тестовом хранилище (относительно корня проекта)
const TEST_VAULT_PLUGIN_DIR = "TestVault/SidecarTest/.obsidian/plugins/ObsidianSidecarCreator";

// true = удалять папку целиком перед копированием (чистая установка)
// false = просто перезаписывать файлы (быстрее, меньше риск блокировки файлов)
const FULL_REBUILD = false;

// ================================

const copyToTestVaultPlugin = {
	name: 'copy-to-test-vault',
	setup(build) {
		build.onEnd(() => {
			const targetDir = path.resolve(process.cwd(), TEST_VAULT_PLUGIN_DIR);

			// Если выбран режим полного удаления (FULL_REBUILD = true)
			if (FULL_REBUILD && fs.existsSync(targetDir)) {
				try {
					fs.rmSync(targetDir, { recursive: true, force: true });
					console.log(`[Clean] Удалена старая папка: ${TEST_VAULT_PLUGIN_DIR}`);
				} catch (e) {
					console.warn(`[Warning] Не удалось удалить папку (возможно, Obsidian держит файлы):`, e.message);
				}
			}

			// Создаем папку, если её нет
			if (!fs.existsSync(targetDir)) {
				fs.mkdirSync(targetDir, { recursive: true });
			}

			// Список файлов для копирования
			const filesToCopy = ['main.js', 'manifest.json', 'styles.css'];

			filesToCopy.forEach(file => {
				const sourcePath = path.resolve(process.cwd(), file);
				const targetPath = path.join(targetDir, file);

				if (fs.existsSync(sourcePath)) {
					fs.copyFileSync(sourcePath, targetPath);
					console.log(`[Sync] ${file} -> ${TEST_VAULT_PLUGIN_DIR}`);
				}
			});

			// Создаем пустой файл .hotreload для плагина Hot Reload (если используете)
			// fs.writeFileSync(path.join(targetDir, '.hotreload'), '');

			console.log(`⚡ Build finished!`);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyToTestVaultPlugin], // Подключили плагин копирования
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
